version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/savepoint-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/lambdas-py"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
