export const DEFAULT_RATE_LIMIT_REQUESTS = 120;
export const DEFAULT_RATE_LIMIT_WINDOW_MS = 60_000;
export const RATE_LIMIT_CLEANUP_INTERVAL_MS = 10 * 60 * 1000;
export const RATE_LIMIT_RETRY_AFTER_SECONDS = 60;

export const GAME_SEARCH_CACHE_TTL_SECONDS = 300;
export const GAME_SEARCH_STALE_TIME_MS = 5 * 60 * 1000;
export const GAME_SEARCH_GC_TIME_MS = 10 * 60 * 1000;
export const LIBRARY_DATA_STALE_TIME_MS = 30_000;
export const LIBRARY_DATA_GC_TIME_MS = 5 * 60_000;
