export const USERNAME_MIN_LENGTH = 3;
export const USERNAME_MAX_LENGTH = 25;
export const USERNAME_VALIDATION_DEBOUNCE_MS = 500;
export const SUGGESTED_USERNAME_MAX_LENGTH = 20;
export const PROFANITY_MIN_WORD_LENGTH = 4;

export const PASSWORD_MIN_LENGTH = 8;

export const USER_NAME_MIN_LENGTH = 2;
export const USER_NAME_MAX_LENGTH = 50;

export const MIN_SEARCH_QUERY_LENGTH = 3;
export const SEARCH_INPUT_DEBOUNCE_MS = 500;

export const MAX_AVATAR_FILE_SIZE_BYTES = 4 * 1024 * 1024;
