export {
  type RepositoryResult,
  type RepositorySuccess,
  type RepositoryFailure,
  type RepositoryError,
  RepositoryErrorCode,
  repositorySuccess,
  repositoryError,
  isRepositorySuccess,
  isRepositoryError,
  withRepositoryError,
} from "./types";
export {
  createLibraryItem,
  deleteLibraryItem,
  findLibraryItemById,
  updateLibraryItem,
  getLibraryItemsForUserByIgdbId,
  getManyLibraryItems,
  getLibraryCount,
  getPlatformBreakdown,
  getAcquisitionTypeBreakdown,
  getRecentlyCompletedLibraryItems,
  getUniquePlatforms,
  getOtherUsersLibraries,
  getOtherUsersLibrariesPaginated,
  getLibraryByUsername,
  getWantToPlayItemsByUsername,
  findWantToPlayItemsForUser,
  findUpcomingWantToPlayItems,
  findCurrentlyPlayingGames,
  findMostRecentPlayingGame,
  buildCollectionFilter,
  getLibraryStatsByUserId,
  findMostRecentLibraryItemByGameId,
  findAllLibraryItemsByGameId,
  findLibraryItemsWithFilters,
  countLibraryItemsByUserId,
  hasLibraryItemWithStatus,
  type FindLibraryItemsResult,
} from "./library/library-repository";
export {
  getUserBySteamId,
  getUserByUsername,
  updateUserSteamData,
  getUserSteamData,
  getUserInfo,
  updateUserData,
  getUserSteamId,
  disconnectSteam,
  findUserById,
  findUserByNormalizedUsername,
  updateUserProfile,
  findUserByEmail,
  createUserWithCredentials,
  updateOnboardingDismissed,
  getOnboardingStatus,
} from "./user/user-repository";
export {
  upsertGenre,
  upsertGenres,
  findGenreByIgdbId,
} from "./genre/genre-repository";
export {
  upsertPlatform,
  upsertPlatforms,
  findPlatformByIgdbId,
  findPlatformsForGame,
  findSystemPlatforms,
} from "./platform/platform-repository";
export {
  createGameWithRelations,
  findGameBySlug,
  findGameByIgdbId,
  gameExistsByIgdbId,
  findGamesByIds,
  findGameById,
  type GameBasicInfo,
} from "./game/game-repository";
export {
  findJournalEntriesByGameId,
  countJournalEntriesByGameId,
  countJournalEntriesByUserId,
  createJournalEntry,
  findJournalEntryById,
  findJournalEntriesByUserId,
  updateJournalEntry,
  deleteJournalEntry,
} from "./journal/journal-repository";
export {
  upsertManyImportedGames,
  findImportedGamesByUserId,
  countImportedGamesByUserId,
  softDeleteImportedGame,
  type CreateImportedGameInput,
  type ImportedGameQueryOptions,
  type PaginatedImportedGames,
  type PlaytimeStatus,
  type PlaytimeRange,
  type Platform,
  type LastPlayed,
  type SortBy,
} from "./imported-game";
