/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'
import { Route as DevIgdbSearchRouteImport } from './routes/dev/igdb-search'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedLibraryRouteImport } from './routes/_authed/library'
import { Route as AuthedJournalRouteImport } from './routes/_authed/journal'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as UUsernameFollowingRouteImport } from './routes/u.$username.following'
import { Route as UUsernameFollowersRouteImport } from './routes/u.$username.followers'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed/settings/profile'
import { Route as AuthedSettingsAccountRouteImport } from './routes/_authed/settings/account'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIgdbSearchRoute = DevIgdbSearchRouteImport.update({
  id: '/dev/igdb-search',
  path: '/dev/igdb-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLibraryRoute = AuthedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJournalRoute = AuthedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const UUsernameFollowingRoute = UUsernameFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameFollowersRoute = UUsernameFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => UUsernameRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsAccountRoute = AuthedSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/journal': typeof AuthedJournalRoute
  '/library': typeof AuthedLibraryRoute
  '/profile': typeof AuthedProfileRoute
  '/dev/igdb-search': typeof DevIgdbSearchRoute
  '/games/$slug': typeof GamesSlugRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/journal': typeof AuthedJournalRoute
  '/library': typeof AuthedLibraryRoute
  '/profile': typeof AuthedProfileRoute
  '/dev/igdb-search': typeof DevIgdbSearchRoute
  '/games/$slug': typeof GamesSlugRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/journal': typeof AuthedJournalRoute
  '/_authed/library': typeof AuthedLibraryRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/dev/igdb-search': typeof DevIgdbSearchRoute
  '/games/$slug': typeof GamesSlugRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/_authed/settings/account': typeof AuthedSettingsAccountRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/journal'
    | '/library'
    | '/profile'
    | '/dev/igdb-search'
    | '/games/$slug'
    | '/u/$username'
    | '/settings/account'
    | '/settings/profile'
    | '/api/auth/$'
    | '/u/$username/followers'
    | '/u/$username/following'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/journal'
    | '/library'
    | '/profile'
    | '/dev/igdb-search'
    | '/games/$slug'
    | '/u/$username'
    | '/settings/account'
    | '/settings/profile'
    | '/api/auth/$'
    | '/u/$username/followers'
    | '/u/$username/following'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/journal'
    | '/_authed/library'
    | '/_authed/profile'
    | '/dev/igdb-search'
    | '/games/$slug'
    | '/u/$username'
    | '/_authed/settings/account'
    | '/_authed/settings/profile'
    | '/api/auth/$'
    | '/u/$username/followers'
    | '/u/$username/following'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  DevIgdbSearchRoute: typeof DevIgdbSearchRoute
  GamesSlugRoute: typeof GamesSlugRoute
  UUsernameRoute: typeof UUsernameRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/igdb-search': {
      id: '/dev/igdb-search'
      path: '/dev/igdb-search'
      fullPath: '/dev/igdb-search'
      preLoaderRoute: typeof DevIgdbSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library': {
      id: '/_authed/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthedLibraryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/journal': {
      id: '/_authed/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthedJournalRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/u/$username/following': {
      id: '/u/$username/following'
      path: '/following'
      fullPath: '/u/$username/following'
      preLoaderRoute: typeof UUsernameFollowingRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/followers': {
      id: '/u/$username/followers'
      path: '/followers'
      fullPath: '/u/$username/followers'
      preLoaderRoute: typeof UUsernameFollowersRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/account': {
      id: '/_authed/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthedSettingsAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedJournalRoute: typeof AuthedJournalRoute
  AuthedLibraryRoute: typeof AuthedLibraryRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedSettingsAccountRoute: typeof AuthedSettingsAccountRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedJournalRoute: AuthedJournalRoute,
  AuthedLibraryRoute: AuthedLibraryRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedSettingsAccountRoute: AuthedSettingsAccountRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface UUsernameRouteChildren {
  UUsernameFollowersRoute: typeof UUsernameFollowersRoute
  UUsernameFollowingRoute: typeof UUsernameFollowingRoute
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameFollowersRoute: UUsernameFollowersRoute,
  UUsernameFollowingRoute: UUsernameFollowingRoute,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  DevIgdbSearchRoute: DevIgdbSearchRoute,
  GamesSlugRoute: GamesSlugRoute,
  UUsernameRoute: UUsernameRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
